#+DATE: 2026-02-03T09:32:54+02:00
#+TITLE: Success Quest
#+DRAFT: true
#+TYPE: post

SuccessQuest is a strange one! This is an app that didn't get nearly the love that it deserved. It ultimately grew beyond it's own brief by a small team of dedication and passionate individuals.

The love & care that went into the application's crafting is only match by it's awesomeness and short lifespan. It was born from a crazy conversation, got momentum from stakeholders and vendors who where as crazy to go along with the idea, development at a break-neck velocities so that the application could launch on time, burn bright and fall to earth like the shooting start that it was. It wasn't meant to last long, but it should have lasted longer than it did.

The problem statement was a tough one: bring some interactivity and user engagement to an annual 'back to school' stationary product catalog. We had roughly 80 pages of school & office stationary to work with, with a number of stores across South Africa. As we listed a number of possibilities, I suggested using augmented reality. The idea wasn't new but it was somewhat novel. I'd seen similar projects in action (Lego, Ikea) and it was something different for South Africa. It was also the height of 'Pokemon Go' craze, so there was an appetite. I had played with Flar-manager when I was working with Flash, and I was playing with Vuforia & Unity at the time (this was before Arcore & Arkit).

The core idea was that each participating vendor would get an AR marker in the catalog and a marker at their product shelf in store. If someone scanned all the markers, they would be entered into a draw to win some additional prizes. Scanning the markers would turn the stores and catalog into a treasure hunt.

I was the only developer on the project, and I was responsible for co-coordinating efforts across teams and bringing it together in the app. When the concepts for the vendor characters started to come through, the whole team realized that we were onto something. Momentum grew as we got previews of the rendered scenes. The vendors also got more invested in their own characters with each preview and started making suggestions. We incorporated the feedback as best as we could, but the timeline was tight and the team was already at capacity. But the more SuccessQuest came together, the more excited we became and the more time we spent on the project.

I cannot talk to much on the characters, the animations or the scenes as those processes were driven by others. So much of what made SuccessQuest great was within the characters themselves and how the products were re-imagined into distinct personalities. This can be seen in the videos but I cannot take credit for this. My contribution lay in:
- providing the main brief and the an explanation of the AR medium that characters would live in.
- brief the different teams on the constraints, realities & possible pit-falls of the project.
- provide previews of the work so that the team & stakeholders to keep the momentum going.
- bring the assets (create trackers from the physical markers, build the mobile app from the animations) together and build all the supplemental digital resources (marketing website, competition back end).
