#+DATE: 2024-08-01T16:54:36+02:00
#+TITLE: The Void
#+DRAFT: false
#+TYPE: post

{{< img name="void.png" classes="right corners" style="width:180px" alt="Image of a void" >}}
I woke up this morning with a hole in my very center. I felt it immediately, something in me was gone! Something core, replaced by a cold space. A dark void in the shape of a missing piece.{{<break>}}{{<break>}} It's worse than losing a tooth. I would impulsively explore the space to confirm what I already knew. Whatever was there before wasn't there anymore. I obsessively prodded the void, yearning for the familiar comfort that wasn't there. I couldn't stop myself. This core piece, this central part of me that I had taken for granted, was gone. And I had no idea where it was? In its place an unfeeling void.

* Searching
I'm starting to panic! I have turned the house upside down, retraced my steps and nothing. No sign, no trail I could follow or clue I could see. Nothing except my obsessive prodding. And it's not as if I could have misplaced it! It was part of me. A fundamental part of me! I didn't think I could lose it, so I didn't even think to be more protective of it. It was always, always there. And the more I yearned for it, the more the void throbbed.

** Found
I found it! At least, I know where it is! My daughter has it. I don't know how she got hold of it but as I walked past her room I saw her playing with it. Oh the relief to see it again, just to know where it was. I asked her to let me see it but she immediately got suspicious and tried to hide under the bed. And as she ran away with my missing piece, the void started to throb. I'm not used to this pain but it's OK. I'll let her play with it a bit more before I take it back. I'm sure she'll get bored of it soon enough.

** Frustration
I'm getting angry! I've tried a number of times to get the piece back and none of them have worked. I can't even get near it. She holds the piece with a vice-like grip. She not even this protective of her favorite toys. If I sneak into her room while she is sleeping, she starts to stir and moan. The closer I get, the more she stirs. I tried grabbing it but she immediately woke up and gave an inhuman scream. I panicked and ran out her room. My wife arrived and tried to console. It took a very long time for her to calm down. My daughter was incoherent in her sobs, so it was all explained away as a nightmare. While I heard them talk, the void throbbed.

I tried reasoning with her. I asked her where she got my piece? She would simply reply that she 'found' it, then smiled and hugged it closer. When I pushed her for more details, she got suspicious and tried to hide under her bed again. I even tried forcing her to give it to me, raising my voice and preparing to grab it. But it ends the same way. She'd give the same inhuman scream and I would panic and back off immediately. The scream would attract attention, often my wife. My daughter would be incoherent so no cause for the screams was identified. But I'm starting to wonder if getting the piece back is worth the pain I'm inflicting. Both on my daughter and my wife. Still, the void throbs. 

** Acceptance
It has been some time since I've made an attempt at the piece. I don't know where my daughter hides it and my wife can't seem to see it. But it's there. And it's real. And its loss hurts me in ways I can't explain.

I occasionally walk past my daughter's room to see her playing with it. The joy and delight that she gets from it reminds me of the same feelings it gave me. My sadness at loosing it is only matched by the joy I see shine from her. But only barely. If I watch her for too long, she instinctively realises and turns to me. The look she gives is wary and afraid. As if she isn't sure what to do? Whether she needs to run and hide again. But I relent and retreat, leaving her to her world.

And even though I hurt and yearn, I have to accept that the missing piece... it suits her. She seems fuller, more alive with it. At this rate I may never get it back. My love for my daughter is stronger than my pain.

** Observing
I noticed today that my daughter does not carry the piece the way that I did. Even though it is clearly the piece I knew, she has altered it. The parts that made it fit inside me are still there but they have changed slightly. The piece has adjusted to fit her. She carries it better than I did, with a confidence and style I'd lost. I realise I'd had taken it for granted.

But there's more. There is a depth to the piece I never appreciated. My daughter is changing it and this isn't the first time it has changed. I can see her changes. But there are more changes and they were not made by me. There are layers to the piece, very subtle ones. Too many to count. Small changes made over time like the rings of a tree. My daughter isn't changing it. She's adding to it.

** Parents
My parents came for a visit today. It's always great to catch up with them and the children love their visits. The day was relaxed, full of laughs and food. But through it all, I noticed something about my parents. A very subtle stiffness to their motions. Their movements had a practiced grace but betrayed small tell-tale signs: they also had parts of themselves missing.

It wasn't easy to spot. Like an old wound that they've made peace with and compensated for. They sit or move so that it's not facing you. Or stand in a way that keeps it hidden. Once I saw their voids, I saw the subtle and graceful dance to keep their voids concealed. A dance that doesn't exit without a void. 

And it's not a shameful dance. It's a dance of courage. Something happened that hurt but didn't break. It made them stronger and wiser through a lingering loss.

There was a moment when our eyes met while they put on their coats. I could see that they knew I had spotted their voids. And in turn, they could see mine. And the shape of our voids were similar. Mine was newer and still raw. Theirs had a familiar shape but was softer. It was then that we felt the same loss, the same pain. But there was also an understanding. The voids we shared personal and not to be parade. It was a rite of passage shared by those who loved unconditionally. And through that love, gave away the very best of themselves. A precious gift to someone deserving.

We shares a sorrowful but sweet smile. The moment passed, they put on their coats and walked out the door. I see my parents differently now, as well as my children. And my place in between. I am practicing my movements, trying to move as my parents did. As my grandparents did. To build myself anew from what I have left. My motions are still clumsy but I'm getting better. I'm learning to present the pieces of me I still have. And to not draw attention to those I have lost. It still hurts but it's getting better. I'm getting better.

This morning I awoke to find another part of me missing, until I saw my son playing with it.
