baseurl = "https://chrispyke.com/"
languageCode = "en"
title = "Space Cowboy Coding"
enableRobotsTXT = true
disable404 = false
googleAnalyticsID = "G-ELLT1F8NM9"  

[params]
  author = "Chris Pyke"
  description = "Personal blog for Chris Pyke"
  font = "https://fonts.googleapis.com/css?family=Open+Sans:300,600"
