baseurl = "http://chrispyke.com/"
languageCode = "en-us"
title = "chrispyke.com"

[params]
  author = "Chris Pyke"
  description = "Personal blog for Chris Pyke. This includes adventures in code, inspirational articles/ projects and anything that keeps me coding."
