baseurl = "https://chrispyke.com/"
languageCode = "en-za"
title = "Space Cowboy Coding"
enableRobotsTXT = true
disable404 = false
googleAnalytics = "UA-39736751-1"

[params]
  author = "Chris Pyke"
  description = "Personal blog for Chris Pyke."
  dashboardTitle = "We're Live!"
  dashboardDescription = "This has been a long time coming, time to populate with some content."
  
