#+DATE: 2019-06-05T10:09:06+02:00
#+TITLE: Curriculum Vitæ
#+DRAFT: false
#+TYPE: cv

* Work Experience
** Bird (formerly MessageBird)
|------------------------+------------------------|
| Amsterdam, Netherlands | January 2020 - present |
|                        | Software Engineer      |
|------------------------+------------------------|

- Successfully decoupled an existing front-end from an internal-facing system. This allowed for faster & more stable application development.
- Sought after by some teams within the Engineering department. Ability to rekindle relationships resulted in better communication, team dynamics & ramp up times.
- Responsible for feature development on customer facing products as well as internal tooling. Developed & deployed solutions from loose business requirements, often under tight timelines.
- Additional responsibilities included on-call shifts for the tech-stacks as well as providing support for customer-support personnel. 

** Absa (formerly Barclays Africa Group)
|----------------------------+-------------------------------|
| Johannesburg, South Africa | February 2016 - December 2019 |
|                            | Creative Technologist         |
|----------------------------+-------------------------------|

- Introduced the bank to & deployed its first React application. Standardized & scaled these applications across Africa, increasing user engagement.
- Motivated for and created the bank’s first AR & VR capability across three cities. Created AR & VR proof of concepts.
- Consistently delivered high risk or technical briefs.
- Managed three interns remotely to produce augmented reality proof of concepts.
- Established a relationship with the University of Pretoria to better explore user engagement in different digital mediums.

** McCann Worldgroup South Africa
|-----------------------+------------------------------|
| Sandton, South Africa | January 2015 - December 2015 |
|                       | Senior Developer             |
|-----------------------+------------------------------|

- As the only developer in a newly created digital department, I interfaced directly with clients to unpack & define their core objectives.
- Built, deployed, maintained and provided technical direction for all digital projects, often under tight time & budget constraints.
- Supported the project managers, community managers & designers in the execution of their tasks.
- Conceptualised, successfully motivated, built & deployed a cross-device, cross-platform, mobile based augmented reality solution.
- Clients include: /Nestle {{< dot >}}Waltons {{< dot >}}Kauai {{< dot >}}UIP {{< dot >}}Chevrolet {{< dot >}}Isuzu {{< dot >}}Zurich {{< dot >}}Econet/

** Freelance
|------------------------+------------------------------|
| Pretoria, South Africa | January 2014 - December 2014 |
|                        | Multimedia Developer         |
|------------------------+------------------------------|

- Assisted clients to narrow down & define their core objectives.
- Provided technical direction on key technologies & realistic timelines required to achieve objectives.
- Successfully conceptualised, scoped, developed & deployed a number of projects.

** Gloo (merged into Ogilvy South Africa)
|-------------------------+---------------------------|
| Greenside, South Africa | June 2012 - December 2013 |
|                         | Senior Developer          |
|-------------------------+---------------------------|

- Part of a dynamic team of designers & developers known for delivering award winning projects within tight timelines & budgets.
- Called in to assist with crisis or time-critical projects, as well as interface with difficult clients.
- Supported & up-skilled the junior developers & creatives.
- Clients include: /BMW {{< dot >}}FNB {{< dot >}}MINI {{< dot >}}RMB {{< dot >}}Samsung {{< dot >}}SA Tourism/

** LXi
|------------------------+------------------------------|
| Randburg, South Africa | January 2011 - February 2012 |
|                        | Developer                    |
|------------------------+------------------------------|

- As the only developer in the company I successfully scoped, developed & deployed touch, multi-touch and motion capture applications.
- Reverse engineered application development for existing & new devices.
- Interfaced directly with clients to unpack & better understand their core requirements.
- Clients included: /Paragon Group {{< dot >}}PWC {{< dot >}}Sanofi Aventis {{< dot >}}SAP/

** iLogic
|-----------------------+--------------------------|
| Sandton, South Africa | May 2010 - November 2010 |
|                       | Flash & Web Developer    |
|-----------------------+--------------------------|

- Responsible for taking high-pressure briefs from concept through to deployment.
- Successfully planned, developed & deployed projects on desktop, social media & web.
- Deadline driven, consistently delivered projects in the given timelines.

** ILA Vietnam
|----------------+------------------------|
| Hanoi, Vietnam | July 2007 - March 2009 |
|                | English Teacher        |
|----------------+------------------------|

- Provided IELTS preparation, as well as custom classes for business & educational English.
- Commended on my innovative teaching style, vibrancy of my classes & the variety of media used in my lessons.
- Responsible for planning & presenting English classes for a full range of students from young learners to adults.
- Developed teaching resources and presented workshops to my peers around the topics: /“Film & video in the classroom” {{< dot >}}“Interactive software in an educational setting”./

** Aston Schools
|------------------+---------------------------|
| Zhengzhou, China | August 2006 - March 2007  |
|                  | Foreign Manager & Teacher |
|------------------+---------------------------|

- Co-managed a school of 200 students in addition to providing orientation, development & continuous assessment the foreign teachers.
- Responsible for planning & presenting English classes for a full range of students from young learners to adults.
- Planned and delivered activities including: /curriculum development {{< dot >}}delivering promotional classes (all ages) {{< dot >}}promotional field work {{< dot >}}judging English competitions {{< dot >}}creating public English corners./

** Aston Schools
|--------------+------------------------|
| Jinan, China | April 2005 - July 2006 |
|              | Senior Teacher         |
|--------------+------------------------|

- Responsible for planning & presenting English classes for a full range of students from young learners to adults.
- Developed school resources including: /flash-cards {{< dot >}}posters {{< dot >}}authentic materials./

* Other Initiatives
** [[https://www.afrikaburn.com/][AfrikaBurn]]
- *2019:* Build team lead for the 'Sweet Love Gateway' art work.
- Successfully wrote the project proposal & motivated for grants.
- Participated in fundraisers for the project.
- Planned, prototyped, budgeted & successfully executed the project.
- Solely responsible for the lighting of the project, which was made up of 40m/ 2400 individually addressable LED lights.


- *2010:* Assisted with the development & revision of the original website theme.

** University of Pretoria
- Played a pivotal role in industry push towards a focus on virtual reality at the University of Pretoria.
- Invited to present guest lectures to post-graduate & prospective students.
- Invited to join workshops & panels to the benefit of students.

** OppiKoppi
- Successfully conceptualised, motivated for, prototyped & led/ co-led the construction of a number of structures.


- *2017:* Assisted with the construction of the final tower.
- *2015:* Led the construction of the tower & assisted with the construction of the catapult.
- *2014:* Led the construction of the tower & assisted with the construction of the shade dome.
- *2013:* Led the construction of the solo tower.
- *2012:* Led the construction of the medic tower & assisted with the construction of the primary tower.
- *2011:* Led the construction of the newer, bigger tower.
- *2010:* Led the construction of the first tower.

* Education

** [[https://frontendmasters.com/u/Ultrachrisp/][Frontend Masters]]
|--------+--------------------------|
| Online | September 2020 - present |
|--------+--------------------------|

- Deeper understanding of modern development trends
- Opportunity to explore various topics around multiple languages and technology stacks.

** [[https://www.coursera.org/account/accomplishments/certificate/NQ7GJD6E4UZR][Coursera: Machine Learning]]
|--------+---------------------|
| Online | July 2019           |
|        | Stanford University |
|--------+---------------------|

- Provided a solid base for future machine learning projects.

** [[https://www.coursera.org/account/accomplishments/specialization/LQ3SZPLYWTF7][Coursera Specialisation: Python for Everybody]]
|--------+------------------------|
| Online | January 2018           |
|        | University of Michigan |
|--------+------------------------|

- Enjoyable introduction to Python showcasing many features of the language.
- Aimed to use Python for future projects or studies.

** [[https://www.coursera.org/account/accomplishments/specialization/3VS6JECTTJKS][Coursera Specialisation: Functional Programming in Scala]]
|--------+------------------------------------------|
| Online | November 2016 - July 2017                |
|        | École Polytechnique Fédérale de Lausanne |
|--------+------------------------------------------|

- Exposed to new concepts & principles in programming.
- Provided alternatives for many contemporary programming principles & practices.

** CELTA
|----------------------+-------------------------------|
| Ho Chi Minh, Vietnam | September 2006 - October 2006 |
|                      | Cambridge University          |
|----------------------+-------------------------------|

- Passed with a 'Grade A'.
- Deeper & richer understanding of what 'communication' is and how to do it effectively.

** Bachelor of Information Science (Multimedia)
|------------------------+------------------------------|
| Pretoria, South Africa | January 2001 - December 2004 |
|                        | University of Pretoria       |
|------------------------+------------------------------|

Majoring in:
- Computer Science
- Multimedia
- English

* Proficiencies
** Soft Skills
- Substantial communication & interpersonal skills, with a sensitivity to cultures & contexts.
- Strong leadership skills without sacrificing the ability to collaborate or follow.
- Confident presentation skills allowing easy & natural interactions with audiences.
- Good motivator able to establish meaningful interactions within a team.
- Proven problem solving skills complimented with effective application of design thinking processes.
- Excited by a challenge & curious by nature.
- Self-motivated with an aptitude to rapidly up-skill myself in a new technology or framework.

