#+DATE: 2019-06-05T10:09:06+02:00
#+TITLE: Curriculum Vitæ
#+DRAFT: false
#+TYPE: cv

* Work Experience
** Bird (formerly MessageBird)
|------------------------+------------------------|
| Amsterdam, Netherlands | January 2020 - present |
|------------------------+------------------------|
|                        | Software Engineer      |
|------------------------+------------------------|

- Successfully decoupled an existing front-end from an internal-facing system. This allowed for faster & more stable application development.
- Moved between a number of teams within the Engineering department. Often the only developer working on front-end related tasks.
- Sought after by the teams I had worked with. Ability to rekindle relationships resulted in better communication, team dynamics & ramp up times.
- Responsible for feature development on customer facing products as well as internal tooling. Additional responsibilities included on-call shifts for the servers as well as support schedules for customer-support agents. 
- Successfully executed & deployed solutions from loose business requirements, often under tight timelines.

** Absa (formerly Barclays Africa Group Ltd)
|----------------------------+-------------------------------|
| Johannesburg, South Africa | February 2016 - December 2019 |
|----------------------------+-------------------------------|
|                            | Creative Technologist         |
|----------------------------+-------------------------------|

- Introduced the bank to & deployed its first React application. Standardized & scaled these applications across Africa using Adobe Experience Manager (AEM).
- Motivated for and created the bank’s ﬁrst AR & VR capability across three cities. Created a AR & VR proof of concepts for diﬀerent platforms.
- Consistently delivered high risk or technical briefs. This resulted in high exposure campaigns running smoothly & meeting targets.
- Helped establish work flows & pipelines for different portfolios. Contributed to standardizing application development best practices in different teams.
- Contributed to a multi-disciplinary design team on the practical application of the new corporate brand.
- Managed three interns remotely to produce augmented reality proof of concepts.
- Established a relationship with the University of Pretoria to better explore virtual reality, its capabilities & different forms of user engagement.

** McCann Worldgroup South Africa (Pty) Ltd
|------------------------------+-----------------------|
| January 2015 - December 2015 | Sandton, South Africa |
|------------------------------+-----------------------|
|                              | Senior Developer      |
|------------------------------+-----------------------|

- Was the only developer in a newly created digital department.
- Single-handedly built, deployed & maintained many of the projects I was involved with.
- Provided technical direction & insights into numerous technologies & tech-stacks.
- Interfaced directly with clients to unpack & define their core objectives.
- Provided scopes of work, functional specifications as well as process pipelines for projects.
- Successfully deployed projects within the tight time & budget constraints of the client.
- Supported the project managers, community managers & designers in the execution of their tasks.
- Conceptualised, successfully motivated, built & deployed a cross-device, cross-platform, mobile based augmented reality solution.
- Clients include: McCann {{< dot >}}Nestle{{</ dot >}} {{< dot >}}Waltons{{</ dot >}} {{< dot >}}Kauai{{</ dot >}} {{< dot >}}UIP{{</ dot >}} {{< dot >}}Chevrolet{{</ dot >}} {{< dot >}}Isuzu{{</ dot >}} {{< dot >}}Zurich{{</ dot >}} {{< dot >}}Econet{{</ dot >}}

** Freelance
|------------------------------+------------------------|
| January 2014 - December 2014 | Pretoria, South Africa |
|------------------------------+------------------------|
|                              | Multimedia Developer   |
|------------------------------+------------------------|

- Assisted clients to narrow down & define their core objectives.
- Provided technical direction on key technologies & realistic timelines required to achieve objectives.
- Successfully conceptualised, scoped, developed & deployed a number of projects.
- Utilised time to expand knowledge base, streamline development processes & investigate emerging technologies.

** Gloo (merged into Ogilvy South Africa)
|---------------------------+-------------------------|
| June 2012 - December 2013 | Greenside, South Africa |
|---------------------------+-------------------------|
|                           | Senior Developer        |
|---------------------------+-------------------------|

- Responsible for taking high-pressure individual & team briefs from concept through to deployment.
- Successfully & consistently deployed projects within the given time-lines & budgets.
- Called in to assist with crisis or time-critical projects, as well as interface with difficult clients.
- Able to identify process bottle-necks or potential pitfalls & possible ways to mitigate or resolve these issues.
- Provided technical direction for technologies not in the company portfolio.
- Supported & up-skilled the junior developers & creatives.
- Clients include: BMW {{< dot >}}FNB{{</ dot >}} {{< dot >}}MINI{{</ dot >}} {{< dot >}}RMB{{</ dot >}} {{< dot >}}Samsung{{</ dot >}} {{< dot >}}SA Tourism{{</ dot >}}

** LXi
|------------------------------+------------------------|
| January 2011 - February 2012 | Randburg, South Africa |
|------------------------------+------------------------|
|                              | Developer              |
|------------------------------+------------------------|

- Was the only developer in the company.
- Reverse engineered application development for existing & new devices.
- Successfully planned, developed & deployed touch, multi-touch and motion capture applications.
- Researched & implemented technologies for the company.
- Interfaced directly with clients to unpack & better understand their core requirements & objectives.
- Clients included: Paragon Group {{< dot >}}PWC{{</ dot >}} {{< dot >}}Sanofi Aventis{{</ dot >}} {{< dot >}}SAP{{</ dot >}}

** iLogic
|--------------------------+-----------------------|
| May 2010 - November 2010 | Sandton, South Africa |
|--------------------------+-----------------------|
|                          | Flash & Web Developer |
|--------------------------+-----------------------|

- Responsible for taking high-pressure briefs from concept through to deployment.
- Successfully planned, developed & deployed projects on desktop, social media & web.
- Deadline driven, consistently delivered projects in the given timelines.

** ILA Vietnam
|------------------------+-----------------|
| July 2007 - March 2009 | Hanoi, Vietnam  |
|------------------------+-----------------|
|                        | English Teacher |
|------------------------+-----------------|

- Provided IELTS preparation, as well as custom classes for business & educational English.
- Commended on my innovative teaching style, vibrancy of my classes & the variety of media used in my lessons.
- Worked with various PC based learning packages with my students & helped evaluate the effectiveness of these resources.
- Responsible for planning & presenting English classes for a full range of students from young learners to adults.
- Developed teaching resources and presented workshops to my peers around the topics: “Film & video in the classroom” {{< dot >}}“Interactive software in an educational setting”.{{</ dot >}} 

** Aston Schools
|--------------------------+---------------------------|
| August 2006 - March 2007 | Zhengzhou, China          |
|--------------------------+---------------------------|
|                          | Foreign Manager & Teacher |
|--------------------------+---------------------------|

- Co-managed a school of 200 students, 2 foreign teachers, 2 Chinese teachers & a number of Chinese staff.
- Responsible for orientation, development & continuous assessment of the teaching skills of the foreign teachers.
- Developed teaching schedules & provided spread sheet templates for payrolls.
- Responsible for planning & presenting English classes for a full range of students from young learners to adults.
- Planned and delivered promotional activities for the school including: curriculum development {{< dot >}}designing advertisements{{</ dot >}} {{< dot >}}delivering promotional classes (all ages){{</ dot >}} {{< dot >}}promotional field work{{</ dot >}} {{< dot >}}judging English competitions{{</ dot >}} {{< dot >}}creating public English corners.{{</ dot >}}

** Aston Schools
|------------------------+----------------|
| April 2005 - July 2006 | Jinan, China   |
|------------------------+----------------|
|                        | Senior Teacher |
|------------------------+----------------|

- Responsible for planning & presenting English classes for a full range of students from young learners to adults.
- Developed school resources including: flash-cards {{< dot >}}posters{{</ dot >}} {{< dot >}}authentic materials.{{</ dot >}}

* Other Initiatives
** [[https://www.afrikaburn.com/][AfrikaBurn]]
- *2019:* Build team lead for the 'Sweet Love Gateway' art work.
- Successfully proposed the project & motivated for grants.
- Participated in fundraisers for the project.
- Planned, prototyped, budgeted & successfully executed the project.
- Oversaw & coordinated the transportation of equipment to the build site.
- Solely responsible for the lighting of the project, which was made up of 40m/ 2400 individually addressable LED lights.
- Invited to present & share my experiences with a number of interested parties.


- *2010:* Assisted with the development & revision of the original website theme.

** University of Pretoria
- Played a pivotal role in industry push towards a focus on virtual reality at the University of Pretoria.
- Invited to present guest lectures to post-graduate & prospective students.
- Invited to join workshops & panels to the benefit of students.

** OppiKoppi
- Successfully conceptualised, motivated for, prototyped & led/ co-led the construction of a number of structures.
- Part of the core team which coordinated efforts between participants.
- Responsible for sourcing & transporting the equipment.


- *2017:* Assisted with the construction of the final tower.
- *2015:* Led the construction of the tower & assisted with the construction of the catapult.
- *2014:* Led the construction of the tower & assisted with the construction of the shade dome.
- *2013:* Led the construction of the solo tower.
- *2012:* Led the construction of the medic tower & assisted with the construction of the primary tower.
- *2011:* Led the construction of the newer, bigger tower.
- *2010:* Led the construction of the first tower.

* Education

** [[https://frontendmasters.com/u/Ultrachrisp/][Frontend Masters]]
|--------------------------|
| September 2020 - present |
|--------------------------|

- Deeper understanding of modern development trends
- Opportunity to explore various topics around multiple languages and technology stacks.

** [[https://www.coursera.org/account/accomplishments/certificate/NQ7GJD6E4UZR][Coursera: Machine Learning]]
|-----------+---------------------|
| July 2019 | Stanford University |
|-----------+---------------------|

- Provided a solid base for future machine learning projects.
- Better understanding on how to leverage machine learning techniques for computer vision & augmented reality applications.

** [[https://www.coursera.org/account/accomplishments/specialization/LQ3SZPLYWTF7][Coursera Specialisation: Python for Everybody]]
|--------------+------------------------|
| January 2018 | University of Michigan |
|--------------+------------------------|

- Enjoyable introduction to Python showcasing many features of the language.
- Aimed to use Python for future projects or studies.

** [[https://www.coursera.org/account/accomplishments/specialization/3VS6JECTTJKS][Coursera Specialisation: Functional Programming in Scala]]
|---------------------------+------------------------------------------|
| November 2016 - July 2017 | École Polytechnique Fédérale de Lausanne |
|---------------------------+------------------------------------------|

- Exposed to new concepts & principles in programming.
- Provided alternatives for many contemporary principles & practices.
- Provided a deeper insight & appreciation for React.
- Introduction to [[https://spark.apache.org/][Apache Spark]] & large scale data-processing.

** CELTA
|-------------------------------+----------------------|
| September 2006 - October 2006 | Ho Chi Minh, Vietnam |
|-------------------------------+----------------------|
|                               | Cambridge University |
|-------------------------------+----------------------|

- Passed with a 'Grade A'.
- Focused around effective & practical methods for English teaching.
- Empowered me to communicate effectively with elementary English learners.
- Deeper & richer understanding of what 'communication' really is.

** Bachelor of Information Science (Multimedia)
|------------------------------+------------------------|
| January 2001 - December 2004 | Pretoria, South Africa |
|------------------------------+------------------------|
|                              | University of Pretoria |
|------------------------------+------------------------|

Major in Multimedia
- Concerned with the practical application of different communication mediums & paradigms in a digital setting.
- Explored gamification & visual communication via basic design, layout, colour & interaction principles.
- Provided glimpses into what would later become the digital design process including graphic, product, interface, customer & user experience design.

Major in Computer Science
- Concerned with the theory & best practices of  computer programming & software development.
- Explored core concepts including data-structures, design-patterns, programming languages, real-time 3D rendering, networks & security.

Major in English
- Concerned with the history, composition & use of the English language.
- Explored notable periods of literature & their effects on modern English.

* Proficiencies
** Soft Skills
- Substantial communication & interpersonal skills, with a sensitivity to cultures & contexts.
- Strong leadership skills without sacrificing the ability to collaborate or follow.
- Confident presentation skills allowing easy & natural interactions with audiences.
- Good motivator able to establish meaningful interactions within a team.
- Proven problem solving skills complimented with effective application of design thinking processes.
- Excited by a challenge & curious by nature.
- Self-motivated with an aptitude to rapidly up-skill myself in a new technology or framework.

