#+DATE: 2024-08-01T16:54:36+02:00
#+TITLE: The Piece
#+DRAFT: true
#+TYPE: post

* Realisation

I can't say for sure when it happened, but I knew something was very wrong! A part of me was missing. A 'core' part of me was missing, and I had no idea where it was? It was worse than loosing my wallet or passport and more like waking up and a tooth was gone. The space that it filled is now impulsively prodded to confirm what I knew... that it is not there. And even though I knew this, I couldn't 'not' keep poking the empty space. And I knew that the prodding and obsessing achieved nothing, I couldn't stop myself. This core piece, this central part of me was no longer there. And I had no idea where it was?

** Searching
Now I'm getting angry! Have have turned the house upside down, I have retraced my steps for the last couple of weeks and nothing. No sign of the missing piece, no trail I could follow or clue I could see. Just nothing except a hole where it was and my obsessive prodding. And it's not as if I could have misplaced it! It was part of me, a 'core' part of me. I didn't think to handle it more carefully because the thought that I could loose it didn't occur to me. It was always, always there. The thought that it wouldn't be there was, and still is, inconceivable. 

** Found
I found it! At least, I know where it is! My daughter has it. I don't know how she got hold of it, but as I walked past her room I saw her playing with it. I was so relieved to see it again, just to know where it was. I asked her to let me see it but she immediately got suspicious and ran away to hide under the bed. It's OK, I'll let her play with it a bit more before I take it back. I'm sure she'll get bored of it soon enough.

** Frustration
I've tried a number of times to get the piece back, and none of them have worked! Sneaking into her room when she was fast asleep failed. She hugs the peice with a vice-like grip. She doesn't even hold her favourite stuffed animal that hard. I can't even get near it. If I try to sneak into her room while she is sleeping, she starts to stir and moan. I have to back away as carefully in case she wakes up.

I tried reasoning with her too, asking her where she got it? She would simply reply that she 'found' it, and then smile and hold it closer. When pushed for more details, she gets suspicious and tries to hide under her bed again. I even tried forcing her to give it to me, raising my voice or trying to pry her hands from it. Each attempt ended terribly. She would scream like I was hurting her terribly, chilling me to my core. Her grip would tighten even more and together with the screams, I would have to back off quickly. There were a few times when someone would hear and interven. With my previous attempt, my wife heard and came running. She immediately picked up our daughter, trying desparately to consol her. Later, I tried to explain myself to my wife but the angry look she gave me was clear. Nothing could be worth the pain that I appeared to be inflicting on our child.  

** Acceptance
It has been some time since I've made an attempt at getting the peice back. I don't know where my daughter hides it and my wife can't seem to see it. But it's there. And it's real. And it hurts me that I don't have it anymore!

I occasionally walk past my daughters room and see her playing with it. The joy and delight that she gets from it reminds me of the same feelings it gave me. My sadness and pain at loosing it is only barely matched by the way it makes my daughter shine. But if I watch her for too long, she instinctively realises and turns to look at me. The look she gives is wary and somewhat afraid, as if she isn't sure whether she needs to run and hide again. But I relent and back off quickly to let her carry on playing in her own little world. 

And even though it pains me, I have to accept that the piece... suits her. She carries it with a style and confidence that radiates the space around her. I still feel the loss acutely. But I am coming to terms with the fact that it might be a long time before I get the piece back, if ever. My love for my daughter seems to be stronger than the yearning to be complete.

** Observing
I noticed today that my child does not carry the piece the way that I did. Even though it is clearly the piece I knew, they have altered it. The parts that would fit it inside me are still there, but they have changed slighty. The piece has adjusted to fit her. I hate to admit, but she carries it better than I did.

** More
I spotted something else today. I'll admit that I spy on my daughter occasionally when she plays with the piece, but today I spotted something that I never noticed before. The changes made by my daughter to the piece are not the first. Neither were the changes that I had made to it. There are layers on the piece, very subtle ones. Too many to count from the distance that I observe her. And the more I looked at her piece, the more beauty and joy I see radiate from it. I took it for granted, but there is a depth to the piece that that I never appreciated.

** Parents
My parents came for a visit. It's always great to catch up with them and the children are so happy to see them. The day was relaxed and lunch was great but through all the interactions, I noticed something in my parents I hadn't see before. They both carried themselves in a way that wasn't related to their health or age. A very subtle stiffness to their motions, like an old injury that healed years ago that doesn't limit them but still causes a little discomfort. They still laughed and carried on like they always do but when they were getting their coats at the end, I saw why: they also had parts of themselves missing.

It wasn't easy to spot. Like an old wound that they've made peace with, their motions have long compensated for it. They casually sit or move so that it's not facing you, or stand in what seems to be a natural pose but subtly hidden from view. Once you saw the hole, you see all the gracefully motions around keeping it out of view. But you don't see the casual dance they do until you see that there is something missing. That there is something so personal missing that they needed to adjust their whole personality to not showcasing it.

And it's not a shameful dance. I would say they did it with a grace that should amazing courage. Something happened to them, which hurt, but it didn't break them. It made them stronger, wiser even though the loss still lingered with them.

There was a moment where our eyes met while they were putting on their coats. I could see that they knew I had noticed their voids. And in turn, they could see mine. And the shape of our voids were similar. Mine was newer and still raw, where theirs had a familiar shape but softened with the passage of time. In that moment, we felt the sense of loss and pain. But there was also an understanding that it was natural. The void we all shared wasn't shameful, a thing to hide away. But it was so personal that it wasn't something to display to the world either. It was a rite of passage, shared by those who dared to love unconditionally. And ultimately give away the very best of themselves to someone deserving.

We share a sweet but sorrowful smile. The moment passed as they put on their coats and walked out the door. I see my parents differently now, as well as my children, and my place in between. I am practicing my movements now. I'm trying to learn to move as my parents did. As my grandparents did. To build myself anew form what is left. For my motions to gracefully show the parts of me that are still here rather than draw attention to that which is not. It still hurts but it's getting better. I'm getting better.

This morning I woke up and there was another part of me missing, until I saw my son playing with it.
