#+DATE: 2024-08-01T16:54:36+02:00
#+TITLE: The Piece
#+DRAFT: true
#+TYPE: post

* Realisation

I can't say for sure when it happened, but I knew something was very wrong! A part of me was missing. A 'core' part of me was missing, and I had no idea where it was? It was worse than loosing my wallet or passport and more like waking up and a tooth was gone. The space that it filled is now impulsively prodded to confirm what I already knew... that it is not there. And even though I knew this, you couldn't 'not' keep poking the empty space. And I knew that the prodding and obsessing achieved nothing, I couldn't stop myself. This core piece, this central part of me was no longer there and I had no idea where it was?

** Searching
Now I'm getting angry! Have have turned the house upside down, I have retraced my steps for the last couple of weeks and nothing. No sign of the missing piece, no trail I could follow or clue I could see. Just nothing except a hole where it was and my obsessive prodding. And it's not as if I could have misplaced it! It was part of me, a 'core' part of me. The only reason I didn't handle it with more care is that the thought that I could loose it was inconceivable for me. It was always, always there. The thought that it wouldn't be there never occurred to me. 

** Found
I found it! My daughter has it. I don't know how they got hold of it, but as I walked past her room I saw her playing with it. There was such relief at seeing it again, just to know where it was. I asked her to let me see it but she immediately got very upset and tried to hide away under the bed. It's OK, I'll let her play with it a bit more before I take it. She'll get bored of it soon enough.

** Frustration
I've tried a number of times to get the piece back, and none of them have worked! Sneaking into her room when she was fast asleep failed. She hugs the peice with a vice-grip, like a new favorite stuffed toy. I don't even get near it. When she starts to stir and moan. I tried reasoning with her, asking her where she got it? She would reply that says she 'found' it with a smile and hold it closer. When pushed for more details, she gets suspicious and tries to hide under her bed again. I even tried shouting at her a few times, attempting to force her to give it to me. Each time attempt terribly. Whenever I got near it, she would give a scream that chilled me to my core, like I was hurting. Her grip is vice-like, and together with the screams, it's all too much and I would relent before getting hold of it. This is also when someone would hear the screams and interven. The last time, it was my wife. She held our daughter while she wept inconsolibly in her arms. I would try to explain myself, but I would always get the same look and a scolding of nothing can be worth this amount of grief to our child. 

** Acceptance
Even though it pains me, I have to accept that the piece... suits them. They carry it with a style and confidence that is quite amazing. I still feel the loss acutely, but I am coming to terms with the fact that I might not get the piece back. My love for my child is greater than the yearning to be complete.

** Observing
I noticed today that my child does not carry the piece the way that I used to. Even though i can clearly see it's my piece, they have made it their own and adjusted it to their needs. The parts that slotted into me are still there, but a new layer has been added. The piece has been adjusted to suit my child. And even though it hurts to admit, they carry it better than I did.

** More
I saw something else today. I am ashamed to say that I still obsess over the piece, but I spotted something today that I never noticed before. The layer that my child added isn't the only one, nor was my layer the first. There are many layer, too many to acurrately count, that have been added to that piece. And the more I looked at it, the more I saw beauty shine from it in ways that I never appreciated.

** Parents
My parents visited today, and in them I saw holes, and pain, that I never realised were there before. And I recognised the shape of the holes. They were the same shape as mine. Not exactly, but I can could see what should have been there as well as the longing they felt for what they lost. But when I looked in their eyes, I also saw understanding for my loss, and love for a gift passed on. So even though there was a quiet saddness for what we had lost, there was also a real joy at watching my child shine, and play, with these new parts they have found. 

