#+DATE: 2024-08-01T16:54:36+02:00
#+TITLE: The Piece
#+DRAFT: true
#+TYPE: post

* Realisation

I can't say for sure when it happened, but I knew something was very wrong! A part of me was missing. A 'core' part of me was missing, and I had no idea where it was? It was worse than loosing my wallet or passport and more like waking up and a tooth was gone. The space that it filled is now impulsively prodded to confirm what I already knew... that it is not there. And even though I knew this, you couldn't 'not' keep poking the empty space. And I knew that the prodding and obsessing achieved nothing, I couldn't stop myself. This core piece, this central part of me was no longer there and I had no idea where it was?

** Searching
Now I'm getting angry! Have have turned the house upside down, I have retraced my steps for the last couple of weeks and nothing. No sign of the missing piece, no trail I could follow or clue I could see. Just nothing except a hole where it was and my obsessive prodding. And it's not as if I could have misplaced it! It was part of me, a 'core' part of me. The only reason I didn't handle it with more care is that the thought that I could loose it was inconceivable for me. It was always, always there. The thought that it wouldn't be there never occurred to me. 

** Found
So I found the piece today, but I wasn't able to reclaim it. My child has it, and clings to it like it's a new best friend. I don't know how they got hold of it. And I am ashamed to acknowledge the joy I see in their eyes as they obliviously carry on with their childish games, unaware of the pain I am going through. It's OK, I'll let them keep it for a while and I'll take it back when they are asleep. The piece doesn't belong to them anyway.

** Frustration
I've tried a number of times to get the piece back, and none of them have worked! Even if my child is fast asleep and I quietly sneak into their room and try to pry the piece from them, they immediately stir and moan. I even tried to take it while they were playing but it didn't work. As soon as I get close, they get protective and hold on even tighter.

** Acceptance
Even though it pains me, I have to accept the fact that the piece that I have lost to them... suits them. They carry it with a style and confidence that is quite amazing. I still feel the loss acutely, but I am coming to terms with the fact that I might not get the piece back. My love for my child is greater than the yearning to be complete.

** Observing
I noticed today that my child does not carry the piece the way that I used to. Even though i can clearly see it's my piece, they have made it their own and adjusted it to their needs. The parts that slotted into me are still there, but a new layer has been added. The piece has been adjusted to suit my child. And even though it hurts to admit, they carry it better than I did.

** More
I saw something else today. I am ashamed to say that I still obsess over the piece, but I spotted something today that I never noticed before. The layer that my child added isn't the only one, nor was my layer the first. There are many layer, too many to acurrately count, that have been added to that piece. And the more I looked at it, the more I saw beauty shine from it in ways that I never appreciated.

** Parents
My parents visited today, and in them I saw holes, and pain, that I never realised were there before. And I recognised the shape of the holes. They were the same shape as mine. Not exactly, but I can could see what should have been there as well as the longing they felt for what they lost. But when I looked in their eyes, I also saw understanding for my loss, and love for a gift passed on. So even though there was a quiet saddness for what we had lost, there was also a real joy at watching my child shine, and play, with these new parts they have found. 

